from flask import Flask, request, redirect, render_template, send_file
import pandas as pd
from ydata_profiling import ProfileReport
import os

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = 'uploads/'

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/upload', methods=['POST'])
def upload_file():
    if 'file' not in request.files:
        return redirect(request.url)
    file = request.files['file']
    if file.filename == '':
        return redirect(request.url)
    if file:
        file_path = os.path.join(app.config['UPLOAD_FOLDER'], file.filename)
        file.save(file_path)
        try:
            df = pd.read_csv(file_path, encoding='utf-8')
        except UnicodeDecodeError:
            df = pd.read_csv(file_path, encoding='latin1')
        
        profile = ProfileReport(df)
        
        # Extract the base name of the file without extension
        base_name = os.path.splitext(file.filename)[0]
        report_file_name = f"{base_name}_datareport.html"
        report_path = os.path.join(app.config['UPLOAD_FOLDER'], report_file_name)
        profile.to_file(output_file=report_path)
        
        # Modify the generated report to change the navbar and footer
        with open(report_path, 'r') as file:
            report_html = file.read()
        
        
        modified_report_html = report_html.replace('Pandas Profiling Report', 'DataSense')
       
        modified_report_html = modified_report_html.replace('Report generated by YData.', 'Report generated by DataSense.')
        modified_report_html = modified_report_html.replace('href="https://ydata.ai"', '')

        with open(report_path, 'w') as file:
            file.write(modified_report_html)
        
        # Send the file as an attachment
        return send_file(report_path, as_attachment=True)

@app.route('/aboutus')
def about_us():
    return render_template('aboutus.html')

@app.route('/home')
def home():
    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)
